-- Civilization
-- Author: liuxi, chjimmy
--------------------------------------------------------------
INSERT INTO LocalizedText (Language, Tag, Text)
VALUES
	-- City Names
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_1',	'蘭德索爾'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_2',	'美食殿堂'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_3',	'動物苑'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_4',	'伊莉莎白牧場'	),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_5',	'拉比林斯'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_6',	'墨丘利'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_7',	'茜林蒂亞'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_8',	'朱諾'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_9',	'帕拉斯'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_10',	'赫柏'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_11',	'維斯塔'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_12',	'克瑞斯'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_13',	'芙羅拉'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_14',	'墨提斯'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_15',	'伊麗絲'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_16',	'弗麗嘉'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_17',	'洛蕾塔'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_18',	'熱那亞'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_19',	'博洛尼亞'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_20',	'桃樂西亞'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_21',	'尤金妮亞'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_22',	'塔利亞'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_23',	'忒密斯'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_24',	'菲德斯'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_25',	'法埃頓'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_26',	'馬提爾德'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_27',	'雷蒂烏斯'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_28',	'佩特羅'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_29',	'迪茲塔爾'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_30',	'弗泰拉'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_31',	'法斯奇亞'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_32',	'迪克斯提婭'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_33',	'維娜'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_34',	'拉圖斯'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_35',	'斯卡普'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_36',	'普拉諾'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_37',	'紫藤廬'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_38',	'阿克托伊'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_39',	'布裡薩'			),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_40',	'聖特蕾莎'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_41',	'純白之翼'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_42',	'破曉之星'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_43',	'月光學院'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_44',	'暮光流星群'		),
	('zh_Hant_HK',	'LOC_CITY_NAME_PrincessConnectRedive_45',	'黃昏都市'		),
--------------------------------------------------------------
	-- Citizen Names
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_1',	'出雲宮子'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_2',	'冰川鏡華'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_3',	'妮儂·朱貝爾'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_4',	'美波鈴奈'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_5',	'宮阪珠希'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_6',	'藤堂秋乃'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_7',	'柏崎栞'			),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_8',	'喜屋武香織'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_9',	'安芸真琴'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_10',	'姬宮真步'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_11',	'天野鈴莓'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_12',	'佐佐木咲戀'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_13',	'柏崎初音'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_14',	'星野靜流'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_15',	'衣之咲璃乃'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_16',	'櫻井望'			),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_17',	'三角千歌'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_18',	'草野優衣'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_19',	'繭宮紡希'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_20',	'園上矛依未'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_21',	'風宮依裡'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_22',	'風宮茜裡'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_23',	'白銀純'			),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_24',	'克莉絲提娜'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_25',	'禦久間智'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_26',	'北條綾音'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_27',	'栗林胡桃'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_28',	'霧原香澄'		),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_29',	'莉瑪'			),
	('zh_Hant_HK',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_30',	'綾瀨由加莉'		),

--------------------------------------------------------------
	-- Civilization Info
	('zh_Hant_HK',	'LOC_CIVINFO_PrincessConnectRedive_LOCATION',		'阿斯特萊亞'		),
	('zh_Hant_HK',	'LOC_CIVINFO_PrincessConnectRedive_SIZE',			'120,000 km²'	),
	('zh_Hant_HK',	'LOC_CIVINFO_PrincessConnectRedive_POPULATION',		'2000 萬 (2033)'	),
	('zh_Hant_HK',	'LOC_CIVINFO_PrincessConnectRedive_CAPITAL',		'蘭德索爾'		),

--------------------------------------------------------------
	-- Geological Features
	('zh_Hant_HK',	'LOC_NAMED_DESSERT_PCR1',	'熱那亞沙漠'		),
	('zh_Hant_HK',	'LOC_NAMED_DESSERT_PCR2',	'博洛尼亞沙丘'	),
	('zh_Hant_HK',	'LOC_NAMED_LAKE_PCR1',		'芙羅拉湖'		),
	('zh_Hant_HK',	'LOC_NAMED_LAKE_PCR2',		'蘭德索爾湖'		),
	('zh_Hant_HK',	'LOC_NAMED_LAKE_PCR3',		'熱那亞綠洲'		),
	('zh_Hant_HK',	'LOC_NAMED_LAKE_PCR4',		'克瑞斯湖'		),
	('zh_Hant_HK',	'LOC_NAMED_LAKE_PCR5',		'阿斯特朗湖'		),
	('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_PCR1',	'帕拉斯高原'		),
	('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_PCR2',	'弗麗嘉高原'		),
	('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_PCR3',	'忒密斯雪山'		),
	('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_PCR4',	'馬提爾德岩峰'	),
	('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_PCR5',	'雷蒂烏斯群峰'	),
	('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_PCR6',	'弗泰拉斷崖'		),
	('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_PCR7',	'歐拉爾高山'		),
	('zh_Hant_HK',	'LOC_NAMED_OCEAN_PCR1',		'阿斯特萊亞洋'	),
	('zh_Hant_HK',	'LOC_NAMED_RIVER_PCR1',		'維斯塔河'		),
	('zh_Hant_HK',	'LOC_NAMED_RIVER_PCR2',		'墨提斯河'		),
	('zh_Hant_HK',	'LOC_NAMED_RIVER_PCR3',		'迪茲塔爾河'		),
	('zh_Hant_HK',	'LOC_NAMED_RIVER_PCR4',		'朱諾江'			),
	('zh_Hant_HK',	'LOC_NAMED_RIVER_PCR5',		'伊麗絲河'		),
	('zh_Hant_HK',	'LOC_NAMED_SEA_PCR1',		'洛蕾塔海'		),
	('zh_Hant_HK',	'LOC_NAMED_SEA_PCR2',		'馬耳岡海'		),
	('zh_Hant_HK',	'LOC_NAMED_SEA_PCR3',		'墨提斯灣'		),
	('zh_Hant_HK',	'LOC_NAMED_VOLCANO_PCR1',	'尤金妮亞火山'	),
	('zh_Hant_HK',	'LOC_NAMED_VOLCANO_PCR2',	'塔利亞火山'		),
	('zh_Hant_HK',	'LOC_NAMED_VOLCANO_PCR3',	'威裡奧火山'		),
	('zh_Hant_HK',	'LOC_NAMED_VOLCANO_PCR4',	'水晶山'			),

--------------------------------------------------------------
	-- InGame Text
	('zh_Hant_HK',	'LOC_GUILD_CLAN_CITY_PRODUCTION',
		'+{1_num} [ICON_Production] 生產力來自相鄰市中心。'
	),
	('zh_Hant_HK',	'LOC_GUILD_CLAN_NEIGHBOURHOOD_PRODUCTION',
		'+{1_num} [ICON_Production] 生產力來自相鄰社區。'
	),
	('zh_Hant_HK',	'LOC_COMBAT_PREVIEW_TRAIT_CIVILIZATION_PrincessConnectRedive_UA',
		'與魔物和城邦作戰時 +5 [ICON_Strength] 戰鬥力'
	),

	('zh_Hant_HK',	'LOC_PEDIA_LEADERS_PAGE_PCR_KYARU_QUOTE',
		'完美完美！我的進步很大嘛♪ 我果然只要想做就能做到！'
	),
	('zh_Hant_HK',	'LOC_PEDIA_LEADERS_PAGE_PCR_PECORINE_QUOTE',
		'跟最喜歡的人們，一起吃著最喜愛的料理，不管得多努力我都願意！'
	),
	('zh_Hant_HK',	'LOC_PEDIA_LEADERS_PAGE_PCR_KOKKORO_QUOTE',
		'能有幸照顧主人，在下真的是這個世界上最幸福的人♪'
	),

	('zh_Hant_HK',	'LOC_PROJECT_CLAN_BATTLE_NAME',		'公會戰'		),
	('zh_Hant_HK',	'LOC_PROJECT_CLAN_BATTLE_DESCRIPTION',
		'基於區域的專案，每回合提供額外 [ICON_Gold] 金幣和忠誠度，完成時獲得大商人點數和大將軍點數。'
	);