-- Civilization_Config
-- Author: liuxi
--------------------------------------------------------------
INSERT INTO	Types (Type, Kind)
VALUES ('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'KIND_CIVILIZATION');

INSERT INTO	Civilizations(
	CivilizationType,
	Name,
	Description,
	Adjective,
	StartingCivilizationLevelType,
	Ethnicity,
	RandomCityNameDepth
) VALUES (
	'CIVILIZATION_PRINCESS_CONNECT_REDIVE',
	'LOC_CIVILIZATION_PRINCESS_CONNECT_REDIVE_NAME',
	'LOC_CIVILIZATION_PRINCESS_CONNECT_REDIVE_DESCRIPTION',
	'LOC_CIVILIZATION_PRINCESS_CONNECT_REDIVE_ADJECTIVE',
	'CIVILIZATION_LEVEL_FULL_CIV',
	'ETHNICITY_EURO',
	10
);

INSERT INTO	Leaders (LeaderType, Name, InheritFrom, SceneLayers)
VALUES ('LEADER_PCR_KYARU', 'LOC_LEADER_PCR_KYARU_NAME', 'LEADER_DEFAULT', 4);

INSERT INTO	CivilizationLeaders (CivilizationType, LeaderType, CapitalName)
VALUES ('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LEADER_PCR_KYARU', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_1');

--------------------------------------------------------------
INSERT INTO	CityNames (CivilizationType, CityName)
VALUES	('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_1'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_2'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_3'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_4'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_5'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_6'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_7'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_8'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_9'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_10'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_11'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_12'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_13'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_14'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_15'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_16'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_17'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_18'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_19'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_20'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_21'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_22'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_23'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_24'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_25'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_26'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_27'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_28'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_29'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_30'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_31'),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITY_NAME_PRINCESS_CONNECT_REDIVE_32');

--------------------------------------------------------------
INSERT INTO	CivilizationCitizenNames (CivilizationType, CitizenName, Female)
VALUES	('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_MALE_1'  , 0),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_1', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_2', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_3', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_4', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_5', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_6', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_7', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_8', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_9', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_10', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_11', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_12', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_13', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_14', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_15', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_16', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_17', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_18', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_19', 1),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CITIZEN_PRINCESS_CONNECT_REDIVE_FEMALE_20', 1);

--------------------------------------------------------------
INSERT INTO	CivilizationInfo (CivilizationType, Header, Caption, SortIndex)
VALUES	('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CIVINFO_LOCATION'  , 'LOC_CIVINFO_PRINCESS_CONNECT_REDIVE_LOCATION'  , 10),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CIVINFO_SIZE'      , 'LOC_CIVINFO_PRINCESS_CONNECT_REDIVE_SIZE'      , 20),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CIVINFO_POPULATION', 'LOC_CIVINFO_PRINCESS_CONNECT_REDIVE_POPULATION', 30),
		('CIVILIZATION_PRINCESS_CONNECT_REDIVE', 'LOC_CIVINFO_CAPITAL'   , 'LOC_CIVINFO_PRINCESS_CONNECT_REDIVE_CAPITAL'   , 40);