-- Civilization
-- Author: liuxi
--------------------------------------------------------------
INSERT INTO LocalizedText (Language, Tag, Text)
VALUES
	-- City Names
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_1',	'兰德索尔'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_2',	'美食殿堂'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_3',	'动物苑'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_4',	'伊丽莎白牧场'	),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_5',	'拉比林斯'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_6',	'墨丘利'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_7',	'茜林蒂亚'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_8',	'朱诺'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_9',	'帕拉斯'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_10',	'赫柏'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_11',	'维斯塔'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_12',	'克瑞斯'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_13',	'弗洛拉'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_14',	'墨提斯'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_15',	'伊丽丝'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_16',	'弗丽嘉'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_17',	'洛蕾塔'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_18',	'热那亚'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_19',	'博洛尼亚'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_20',	'多萝西亚'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_21',	'尤金妮亚'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_22',	'塔利亚'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_23',	'忒密斯'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_24',	'菲德斯'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_25',	'法埃顿'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_26',	'马提尔德'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_27',	'雷蒂乌斯'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_28',	'佩特罗'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_29',	'迪兹塔尔'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_30',	'弗泰拉'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_31',	'法斯奇亚'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_32',	'迪克斯提娅'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_33',	'维娜'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_34',	'拉图斯'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_35',	'斯卡普'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_36',	'普拉诺'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_37',	'紫藤庐'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_38',	'阿克托伊'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_39',	'布里萨'			),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_40',	'圣特蕾莎'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_41',	'纯白之翼'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_42',	'破晓之星'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_43',	'月光学院'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_44',	'暮光流星群'		),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_45',	'黄昏都市'		),
--------------------------------------------------------------
	-- Citizen Names
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_1',	'出云宫子'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_2',	'冰川镜华'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_3',	'妮侬·朱贝尔'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_4',	'美波铃奈'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_5',	'宫坂珠希'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_6',	'藤堂秋乃'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_7',	'柏崎栞'			),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_8',	'喜屋武香织'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_9',	'安芸真琴'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_10',	'姬宫真步'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_11',	'天野铃莓'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_12',	'佐佐木咲恋'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_13',	'柏崎初音'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_14',	'星野静流'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_15',	'衣之咲璃乃'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_16',	'樱井望'			),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_17',	'三角千歌'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_18',	'草野优衣'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_19',	'茧宫纺希'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_20',	'园上矛依未'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_21',	'风宫依里'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_22',	'风宫茜里'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_23',	'白银纯'			),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_24',	'克莉丝提娜'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_25',	'御久间智'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_26',	'北条绫音'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_27',	'栗林胡桃'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_28',	'雾原香澄'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_29',	'莉玛'			),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_30',	'绫濑由加莉'		),

--------------------------------------------------------------
	-- Civilization Info
	('zh_Hans_CN',	'LOC_CIVINFO_PrincessConnectRedive_LOCATION',		'阿斯特莱亚'		),
	('zh_Hans_CN',	'LOC_CIVINFO_PrincessConnectRedive_SIZE',			'120,000 km²'	),
	('zh_Hans_CN',	'LOC_CIVINFO_PrincessConnectRedive_POPULATION',		'2000 万 (2033)'	),
	('zh_Hans_CN',	'LOC_CIVINFO_PrincessConnectRedive_CAPITAL',		'兰德索尔'		),

--------------------------------------------------------------
	-- Geological Features
	('zh_Hans_CN',	'LOC_NAMED_DESSERT_PCR1',	'热那亚沙漠'		),
	('zh_Hans_CN',	'LOC_NAMED_DESSERT_PCR2',	'博洛尼亚沙丘'	),
	('zh_Hans_CN',	'LOC_NAMED_LAKE_PCR1',		'弗洛拉湖'		),
	('zh_Hans_CN',	'LOC_NAMED_LAKE_PCR2',		'兰德索尔湖'		),
	('zh_Hans_CN',	'LOC_NAMED_LAKE_PCR3',		'热那亚绿洲'		),
	('zh_Hans_CN',	'LOC_NAMED_LAKE_PCR4',		'克瑞斯湖'		),
	('zh_Hans_CN',	'LOC_NAMED_LAKE_PCR5',		'阿斯特朗湖'		),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_PCR1',	'帕拉斯高原'		),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_PCR2',	'弗丽嘉高原'		),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_PCR3',	'忒密斯雪山'		),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_PCR4',	'马提尔德岩峰'	),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_PCR5',	'雷蒂乌斯群峰'	),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_PCR6',	'弗泰拉断崖'		),
	('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_PCR7',	'欧拉尔高山'		),
	('zh_Hans_CN',	'LOC_NAMED_OCEAN_PCR1',		'阿斯特莱亚洋'	),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_PCR1',		'维斯塔河'		),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_PCR2',		'墨提斯河'		),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_PCR3',		'迪兹塔尔河'		),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_PCR4',		'朱诺江'			),
	('zh_Hans_CN',	'LOC_NAMED_RIVER_PCR5',		'伊丽丝河'		),
	('zh_Hans_CN',	'LOC_NAMED_SEA_PCR1',		'洛蕾塔海'		),
	('zh_Hans_CN',	'LOC_NAMED_SEA_PCR2',		'马耳冈海'		),
	('zh_Hans_CN',	'LOC_NAMED_SEA_PCR3',		'墨提斯湾'		),
	('zh_Hans_CN',	'LOC_NAMED_VOLCANO_PCR1',	'尤金妮亚火山'	),
	('zh_Hans_CN',	'LOC_NAMED_VOLCANO_PCR2',	'塔利亚火山'		),
	('zh_Hans_CN',	'LOC_NAMED_VOLCANO_PCR3',	'威里奥火山'		),
	('zh_Hans_CN',	'LOC_NAMED_VOLCANO_PCR4',	'水晶山'			),

--------------------------------------------------------------
	-- InGame Text
	('zh_Hans_CN',	'LOC_GUILD_CLAN_CITY_PRODUCTION',
		'+{1_num} [ICON_Production] 生产力来自相邻市中心。'
	),
	('zh_Hans_CN',	'LOC_GUILD_CLAN_NEIGHBOURHOOD_PRODUCTION',
		'+{1_num} [ICON_Production] 生产力来自相邻社区。'
	),
	('zh_Hans_CN',	'LOC_COMBAT_PREVIEW_TRAIT_CIVILIZATION_PrincessConnectRedive_UA',
		'与魔物和城邦作战时 +5 [ICON_Strength] 战斗力'
	),

	('zh_Hans_CN',	'LOC_PEDIA_LEADERS_PAGE_PCR_KYARU_QUOTE',
		'完美完美！我的进步很大嘛♪ 我果然只要想做就能做到！'
	),
	('zh_Hans_CN',	'LOC_PEDIA_LEADERS_PAGE_PCR_PECORINE_QUOTE',
		'跟最喜欢的人们，一起吃着最喜爱的料理，不管得多努力我都愿意！'
	),
	('zh_Hans_CN',	'LOC_PEDIA_LEADERS_PAGE_PCR_KOKKORO_QUOTE',
		'能有幸照顾主人，在下真的是这个世界上最幸福的人♪'
	),

	('zh_Hans_CN',	'LOC_PROJECT_CLAN_BATTLE_NAME',		'公会战'		),
	('zh_Hans_CN',	'LOC_PROJECT_CLAN_BATTLE_DESCRIPTION',
		'基于区域的项目，每回合提供额外 [ICON_Gold] 金币和忠诚度，完成时获得大商人点数和大将军点数。'
	);