-- Civilization
-- Author: liuxi
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES
	-- City Names
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_1',	'兰德索尔'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_2',	'美食殿堂'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_3',	'动物苑'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_4',	'伊丽莎白牧场'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_5',	'拉比林斯'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_6',	'墨丘利'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_7',	'茜林蒂亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_8',	'朱诺'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_9',	'帕拉斯'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_10',	'赫柏'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_11',	'维斯塔'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_12',	'克瑞斯'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_13',	'弗洛拉'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_14',	'墨提斯'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_15',	'伊丽丝'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_16',	'弗丽嘉'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_17',	'洛蕾塔'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_18',	'热亚那'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_19',	'博洛尼亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_20',	'多萝西亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_21',	'尤金妮亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_22',	'塔利亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_23',	'赛梅斯'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_24',	'菲德斯'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_25',	'法埃顿'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_26',	'马提尔德'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_27',	'雷蒂乌斯'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_28',	'佩特罗'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_29',	'迪兹塔尔'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_30',	'弗泰拉'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_31',	'法斯奇亚'),
	('zh_Hans_CN',	'LOC_CITY_NAME_PrincessConnectRedive_32',	'维娜'),
--------------------------------------------------------------
	-- Citizen Names
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_MALE_1',		'虹村雪'			),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_1',	'出云宫子'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_2',	'冰川镜华'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_3',	'妮侬·朱贝尔'	),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_4',	'美波铃奈'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_5',	'宫坂珠希'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_6',	'藤堂秋乃'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_7',	'柏崎栞'			),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_8',	'喜屋武香织'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_9',	'安芸真琴'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_10',	'姬宫真步'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_11',	'天野铃莓'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_12',	'佐佐木咲恋'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_13',	'柏崎初音'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_14',	'星野静流'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_15',	'衣之咲璃乃'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_16',	'樱井望'			),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_17',	'三角千歌'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_18',	'草野优衣'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_19',	'茧宫纺希'		),
	('zh_Hans_CN',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_20',	'园上矛依未'		),

--------------------------------------------------------------
	-- Civilization Info
	('zh_Hans_CN',	'LOC_CIVINFO_PrincessConnectRedive_LOCATION',		'阿斯特莱亚'		),
	('zh_Hans_CN',	'LOC_CIVINFO_PrincessConnectRedive_SIZE',			'120,000 km²'	),
	('zh_Hans_CN',	'LOC_CIVINFO_PrincessConnectRedive_POPULATION',		'c. 1500 万'		),
	('zh_Hans_CN',	'LOC_CIVINFO_PrincessConnectRedive_CAPITAL',		'兰德索尔'		);