-- Kokkoro
-- Author: liuxi
--------------------------------------------------------------
INSERT INTO LocalizedText (Language, Tag, Text)
VALUES
	('zh_Hans_CN',	'LOC_AGENDA_PCR_KOKKORO_NAME',
		'爱梅斯的神使'
	),
	('zh_Hans_CN',	'LOC_AGENDA_PCR_KOKKORO_DESCRIPTION',
		'喜欢建造其宗教建筑的文明，讨厌皈依其他宗教、或与信奉其宗教城市开战的文明。'
	),
	('zh_Hans_CN',	'LOC_DIPLO_KUDO_EXIT_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_EXIT_LEADER_PCR_KOKKORO_ANY',
		''
	),/* Prolg Scene 2 */
	('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_LEADER_PCR_KOKKORO_ANY',
		'哦呀？终于见到您了，我是[NEWLINE]伟大的爱梅斯大人派来的“引导者”……名为可可萝，请多指教。'
	),
	('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		''
	),/* Prolg Scene 2 */
	('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_PCR_KOKKORO_ANY',
		'咦，怎么愣住了？那个，不好意思……[NEWLINE]能再告知一下您的名字和住处吗？'
	),/* Prolg Scene 2 */
	('zh_Hans_CN',	'LOC_DIPLO_GREETING_LEADER_PCR_KOKKORO_ANY',
		'就让我来引导您吧，请放心。'
	),/* Act 1 Scene 1 */
	('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		'嗯，我会让她们好好休息……随心所欲，尽情玩乐，尝遍美食。'
	),
	('zh_Hans_CN',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		''
	),/* Act 1 Scene 4 */
	('zh_Hans_CN',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		'这样啊……这么短的时间里，您到底想和多少女孩子变得要好啊？'
	),
	('zh_Hans_CN',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		''
	),/* Prolg Scene 2 */
	('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		'嗯，太好了，您就是我要侍奉的主人没错。'
	),/* Act 1 Scene 1 */
	('zh_Hans_CN',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		'虽然有些遗憾……[NEWLINE]若这是主人的想法，我会尊重的。'
	),/* Prolg Scene 2 */
	('zh_Hans_CN',	'LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		'我会守护您，从清晨到夜晚……从出生到死亡，都会全心全意的照顾主人，这就是我的使命。[NEWLINE]主人，有事尽管吩咐。'
	),/* Act 1 Scene 1 */
	('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		'那么，就这么办吧。'
	),
	('zh_Hans_CN',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_AI_RESPONSE_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		''
	),
	('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_AI_RESPONSE_NEGATIVE_LEADER_PCR_KOKKORO_ANY',
		''
	);