-- Civilization
-- Author: liuxi
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES
	-- City Names
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_1',   'Landsol'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_2',   'Gourmet Edifice'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_3',   'Caon'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_4',   'Elizabeth Park'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_5',   'Labyrinth'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_6',   'Carmina'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_7',   'Sarendia'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_8',   'Juno'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_9',   'Pallas'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_10',  'Hebe'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_11',  'Vesta'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_12',  'Ceres'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_13',  'Flora'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_14',  'Metis'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_15',  'Iris'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_16',  'Frigga'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_17',  'Loretta'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_18',  'Genua'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_19',  'Bononia'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_20',  'Dorothea'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_21',  'Eugenia'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_22',  'Taria'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_23',  'Themis'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_24',  'Fides'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_25',  'Faeton'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_26',  'Matildo'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_27',  'Redius'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_28',  'Petero'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_29',  'Dystal'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_30',  'Futera'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_31',  'Faskia'),
	('en_US',	'LOC_CITY_NAME_PrincessConnectRedive_32',  'Hveen'),
--------------------------------------------------------------
	-- Citizen Names
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_MALE_1',		'Nijimura Yuki'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_1',	'Izumo Miyako'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_2',	'Hikawa Kyouka'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_3',	'Joubert Ninon'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_4',	'Suzuna Minami'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_5',	'Miyasaka Tamaki'		),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_6',	'Toudou Akino'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_7',	'Kashiwazaki Shiori'	),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_8',	'Kyan Kaori'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_9',	'Aki Makoto'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_10',	'Himemiya Maho'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_11',	'Amano Suzume'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_12',	'Sasaki Saren'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_13',	'Kashiwazaki Hatsune'	),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_14',	'Hoshino Shizuru'		),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_15',	'Inosaki Rino'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_16',	'Sakurai Nozomi'		),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_17',	'Chika Misumi'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_18',	'Kusano Yui'			),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_19',	'Mayumiya Tsumugi'		),
	('en_US',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_20',	'Sonoue Muimi'			),

--------------------------------------------------------------
	-- Civilization Info
	('en_US',	'LOC_CIVINFO_PrincessConnectRedive_LOCATION',		'Astraea'			),
	('en_US',	'LOC_CIVINFO_PrincessConnectRedive_SIZE',			'120,000 km²'		),
	('en_US',	'LOC_CIVINFO_PrincessConnectRedive_POPULATION',		'c. 15 million'		),
	('en_US',	'LOC_CIVINFO_PrincessConnectRedive_CAPITAL',		'Landsol'			);