-- Kokkoro
-- Author: liuxi
--------------------------------------------------------------
INSERT INTO LocalizedText (Language, Tag, Text)
VALUES
	('en_US',	'LOC_AGENDA_PCR_KOKKORO_NAME',
		'Apostle of Ames'
	),
	('en_US',	'LOC_AGENDA_PCR_KOKKORO_DESCRIPTION',
		'Likes civilizations build her Worship buildings, dislike civilizations following other religions or attacking followers of her religion.'
	),
	('en_US',	'LOC_DIPLO_KUDO_EXIT_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_EXIT_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_FIRST_MEET_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_GREETING_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_AI_RESPONSE_POSITIVE_LEADER_PCR_KOKKORO_ANY',
		""
	),
	('en_US',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_AI_RESPONSE_NEGATIVE_LEADER_PCR_KOKKORO_ANY',
		""
	);