-- Civilization
-- Author: liuxi, Yuki
--------------------------------------------------------------
INSERT INTO LocalizedText (Language, Tag, Text)
VALUES
	-- City Names
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_1',   'ランドソル'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_2',   '美食殿'),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_3',   '自警団(カォン)'			),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_4',   '牧場(エリザベスパーク)'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_5',   'ラビリンス'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_6',   'カルミナ'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_7',   'サレンディア救護院'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_8',   'ジュノー'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_9',   'パラス'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_10',  'ヘーベ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_11',  'ベスタ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_12',  'ケレス'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_13',  'フローラ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_14',  'メティス'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_15',  'イリス'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_16',  'フリガ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_17',  'ロレッタ'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_18',  'ゲヌア'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_19',  'ボノニア'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_20',  'ドロテア'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_21',  'ウジュニア'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_22',  'タリア'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_23',  'テミス'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_24',  'フィデス'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_25',  'ファエトン'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_26',  'マティルド'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_27',  'レディウス'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_28',  'ペテロ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_29',  'ディズタル'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_30',  'フテラ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_31',  'ファスキア'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_32',  'デクスティア'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_33',  'ヴェーナ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_34',  'ラトゥス'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_35',  'スカプ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_36',  'プラノ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_37',  'ウィスタリア'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_38',  'アクドーイ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_39',  'ブリッサ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_40',  '聖テレサ'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_41',  'ヴァイスフリューゲル'),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_42',  'トゥインクルウィッシュ'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_43',  'ルーセント学院'		),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_44',  'トワイライトキャラバン'	),
	('ja_JP',	'LOC_CITY_NAME_PrincessConnectRedive_45',  '黄昏の都'			),
--------------------------------------------------------------
	-- Citizen Names
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_1',	'出雲 宮子'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_2',	'氷川 鏡華'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_3',	'ニノン・ジュベール'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_4',	'美波 鈴奈'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_5',	'宮坂 たまき'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_6',	'藤堂 秋乃'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_7',	'柏崎 栞'	),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_8',	'喜屋 武香織'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_9',	'安芸 真琴'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_10',	'姫宮 真歩'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_11',	'天野 すずめ'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_12',	'佐々木 咲恋'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_13',	'柏崎 初音'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_14',	'星野 静流'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_15',	'衣之咲 璃乃'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_16',	'桜井 望'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_17',	'三角 千歌'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_18',	'草野 優衣'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_19',	'繭宮 つむぎ'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_20',	'園上 矛衣未'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_21',	'風宮 より'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_22',	'風宮 あかり'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_23',	'白銀 純'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_24',	'クリスティーナ・モーガン'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_25',	'御久間 智'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_26',	'北条 綾音'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_27',	'栗林 くるみ'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_28',	'霧原 香澄'		),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_29',	'モニカ・ヴァイスヴィント'			),
	('ja_JP',	'LOC_CITIZEN_PrincessConnectRedive_FEMALE_30',	'綾瀬 ゆかり'		),

--------------------------------------------------------------
	-- Civilization Info
	('ja_JP',	'LOC_CIVINFO_PrincessConnectRedive_LOCATION',		'アストライア'			),
	('ja_JP',	'LOC_CIVINFO_PrincessConnectRedive_SIZE',			'120,000 km²'		),
	('ja_JP',	'LOC_CIVINFO_PrincessConnectRedive_POPULATION',		'2000万 (2033)'	),
	('ja_JP',	'LOC_CIVINFO_PrincessConnectRedive_CAPITAL',		'ランドソル'			),

--------------------------------------------------------------
	-- Geological Features
	('ja_JP',	'LOC_NAMED_DESSERT_PCR1',	'ゲヌア砂漠'		),
	('ja_JP',	'LOC_NAMED_DESSERT_PCR2',	'ボノニア砂丘'		),
	('ja_JP',	'LOC_NAMED_LAKE_PCR1',		'フローラ湖'		),
	('ja_JP',	'LOC_NAMED_LAKE_PCR2',		'ランドソル湖'		),
	('ja_JP',	'LOC_NAMED_LAKE_PCR3',		'ゲヌアオアシス'		),
	('ja_JP',	'LOC_NAMED_LAKE_PCR4',		'ケレス湖'		),
	('ja_JP',	'LOC_NAMED_LAKE_PCR5',		'アストルム湖'		),
	('ja_JP',	'LOC_NAMED_MOUNTAIN_PCR1',	'パラス高原'	),
	('ja_JP',	'LOC_NAMED_MOUNTAIN_PCR2',	'フリガ雪原'	),
	('ja_JP',	'LOC_NAMED_MOUNTAIN_PCR3',	'テミス銀嶺'		),
	('ja_JP',	'LOC_NAMED_MOUNTAIN_PCR4',	'マティルド岩峯'		),
	('ja_JP',	'LOC_NAMED_MOUNTAIN_PCR5',	'レディウス群峯'		),
	('ja_JP',	'LOC_NAMED_MOUNTAIN_PCR6',	'フテラ断崖'		),
	('ja_JP',	'LOC_NAMED_MOUNTAIN_PCR7',	'オラル高山'		),
	('ja_JP',	'LOC_NAMED_OCEAN_PCR1',		'アストライア海'		),
	('ja_JP',	'LOC_NAMED_RIVER_PCR1',		'ベスタ渓谷'		),
	('ja_JP',	'LOC_NAMED_RIVER_PCR2',		'メティス川'		),
	('ja_JP',	'LOC_NAMED_RIVER_PCR3',		'ディズタル川'		),
	('ja_JP',	'LOC_NAMED_RIVER_PCR4',		'ジュノー川'		),
	('ja_JP',	'LOC_NAMED_RIVER_PCR5',		'イリス川'		),
	('ja_JP',	'LOC_NAMED_SEA_PCR1',		'ロレッタ海岸'		),
	('ja_JP',	'LOC_NAMED_SEA_PCR2',		'マルジェン海岸'		),
	('ja_JP',	'LOC_NAMED_SEA_PCR3',		'メティス湾'		),
	('ja_JP',	'LOC_NAMED_VOLCANO_PCR1',	'ウジュニア熱地'		),
	('ja_JP',	'LOC_NAMED_VOLCANO_PCR2',	'タリア火山'		),
	('ja_JP',	'LOC_NAMED_VOLCANO_PCR3',	'ヴェリオ火山'		),
	('ja_JP',	'LOC_NAMED_VOLCANO_PCR4',	'クリスタルマウンテン'	),

--------------------------------------------------------------
	-- InGame Text
	('ja_JP',	'LOC_GUILD_CLAN_CITY_PRODUCTION',
		'隣接する都市の中心部により [ICON_Production] 生産 +{1_num}。'
	),
	('ja_JP',	'LOC_GUILD_CLAN_NEIGHBOURHOOD_PRODUCTION',
		'隣接する近郊部により [ICON_Production] 生産 +{1_num}.'
	),
	('ja_JP',	'LOC_COMBAT_PREVIEW_TRAIT_CIVILIZATION_PrincessConnectRedive_UA',
		'モンスターや敵のユニットと戦うときの [ICON_Strength] 戦闘力 +5'
	),

	('ja_JP',	'LOC_PEDIA_LEADERS_PAGE_PCR_KYARU_QUOTE',
		'完璧！　完璧な仕事だわ。さすが、あたし!!'
	),
	('ja_JP',	'LOC_PEDIA_LEADERS_PAGE_PCR_PECORINE_QUOTE',
		'おいしいご飯のために！'
	),
	('ja_JP',	'LOC_PEDIA_LEADERS_PAGE_PCR_KOKKORO_QUOTE',
		'主様をお守りし、おはようからおやすみまで、ゆりかごから棺桶まで、誠心誠意お世話するのが、わたくしの役目でございます。'
	),

	('ja_JP',	'LOC_PROJECT_CLAN_BATTLE_NAME',		'クランバトル'),
	('ja_JP',	'LOC_PROJECT_CLAN_BATTLE_DESCRIPTION',
		'進行中の都市で [ICON_Gold] ゴールドと忠誠度を上げるプロジェクト。完了時に大商人ポイントと大将軍ポイントを得る。'
	);